### ISSUE TITLE
Catch likely `name.txt` issue

### ISSUE THREAD

**Issue by CatChenal** [GunnerLab/MCCE_ProtInfo#1]
## TODO:
Flag error when `run.log` line contains "not be loaded to conformer type" as a likely issue with `name.txt` file.

## Ancillary task:
  Read `run.prm.record` to retrieve all path keys, so that they can be reported on.
 
## Example (from run.log):
This error occurred due to the minimal name.txt in the mcce conda package.
Although the [mcce repo name.txt](https://github.com/GunnerLab/Stable-MCCE/blob/master/name.txt) does not yet contains a renaming rule for BCL, the atoms listed below, should be renamed to fit the [topology file for BCL](https://github.com/GunnerLab/Stable-MCCE/blob/master/param/bcl.ftpl).  
A more explicit error message could be:
> Error! The following atoms of residue BCL L 282 could not be loaded into its topology conformer BCL-1 because of name mismatches.
```
   Error! The following atoms of residue BCL L 282 can not be loaded to conformer type BCL-1
           NA
           NB
           NC
           ND
           C6
           C7
           C8
           C9
           C10
           C11
           C12
           C13
           C14
           C15
           C16
           C17
           C18
           C19
           C20
   Error! The following atoms of residue BCL L 283 can not be loaded to conformer type BCL-1
   [same atoms]
   Error! The following atoms of residue BCL M 309 can not be loaded to conformer type BCL-1
   [same atoms]
   Error! The following atoms of residue BCL M 310 can not be loaded to conformer type BCL-1
   [same atoms]
```

**Comment by CatChenal** [comment]
(On behave of MG)

Perhaps report error as:
```
Error! The program exited because BCL L 282 could not be loaded into its topology conformer BCL-1. 
This error can occur when the residue has atoms that are not recognized in the topology file. 
Correct the tpl file in directory name or rename atom names using path/name.txt
```
In the "correct the tpl file" line, if you can put in the the path to these that would be great.

**Comment by CatChenal** [comment]
> In the "correct the tpl file" line, if you can put in the the path to these that would be great.  

I'll have to get the path keys from run.prm.record: TODO.

More processing is needed to report this error concisely, i.e. we would not want the have 4 identical messages when there are 4 BCL in the protein. This entails:
 * Gathering the "not be loaded to conformer" lines into a dict(k, list) with conformer type as key.
 * Appending the identifier found between ("because ", " could")
 * [Maybe? Appending another list for the atoms listed.]
 
So the unique message for each key/conformer, here BCL-1, would be:
```
Error! The program exited because BCL (L 282, L 283, M 309, M 310) could not be loaded into its topology conformer BCL-1. 
This error can occur when the residue has atoms that are not recognized in the topology file. 
Correct the tpl file in directory name or rename atom names using path/name.txt
```
Right?

**Comment by mrgunner** [comment]
Cat can you revise the error message?  Looking good. Thanks.
```
Error! The program exited because BCL (L 282, L 283, M 309, M 310) could not be loaded into its topology conformer BCL-1.
This error can occur when the residue has atoms that are not recognized in the topology file.  Look at run.log for a list of atoms in your input pdb file that don't match.
Correct the tpl file in <param directory path> or rename atom names using <name.txt path>.
```
