### ISSUE TITLE
program failure I think it's looking for biopython

### ISSUE THREAD

**Issue by mrgunner** [GunnerLab/MCCE_ProtInfo#12]
(base) gunner@isis:~/test$ which ProtInfo
/home/mcce/MCCE4/MCCE_bin//ProtInfo

It is looking for biopython and fails.
However MCCE  step1 reports cofactors stripped off.  This should be updated in the step1 output so indicate the name of the cofactor and the final count at the end. 

ERROR MESSAGE 
(base) gunner@isis:~/test$ ProtInfo 4lzt.pdb 
Traceback (most recent call last):
  File "/home/mcce/MCCE4/MCCE_bin/ProtInfo", line 7, in <module>
    from mcce4.protinfo.cli import prot_info_cli
  File "/data/home/mcce/MCCE4/MCCE_bin/mcce4/protinfo/cli.py", line 34, in <module>
    from mcce4.protinfo import cli_opts, info, io_utils as iou
  File "/data/home/mcce/MCCE4/MCCE_bin/mcce4/protinfo/info.py", line 25, in <module>
    from mcce4.protinfo import USER_MCCE, bio_parser, log_parser, run
  File "/data/home/mcce/MCCE4/MCCE_bin/mcce4/protinfo/bio_parser.py", line 18, in <module>
    from Bio.PDB.SASA import ShrakeRupley
ModuleNotFoundError: No module named 'Bio.PDB.SASA'

**Comment by CatChenal** [comment]
A per your prompt format, you're in conda's base environment:
>(base) gunner@isis:~/test$ which ProtInfo

The python dependencies have been installed on the server so that WE NO LONGER NEED conda environments.
Run `conda deactivate` at the command line (repeatedly) until your default PS1 prompt re-appears, then rerun the tool or command.
