### ISSUE TITLE
removing biopython (?)

### ISSUE THREAD

**Issue by mrgunner** [GunnerLab/MCCE_ProtInfo#13]
Good info that be gotten pretty easily - read either input protein OR read step1_out.pdb.  biopython is overkill 
The number of chains and amino acids/chain is useful 
The Hetatoms in the pdb file; Just pull this from HET in the pdb file if it's from rcsb. Or report res not on the list of the 20 aa
-->Hetatoms that MCCE doesnt' know.  These are reported in the step1 log file

MCCE reports the cofactors that are stripped off so we don't need biopython to do that.  But the output from MCCE should be enhanced.

But Cat for now remove the biopython calls and let's see what's left and then add back what will be useful.

**Comment by CatChenal** [comment]
ok
